spring:
  application:
    name: product-command-service
rest:
  poolMaxTotal: 200
  poolMaxPerRoute: 50
  connectionRequestTimeout: 4000
  connectTimeout: 4000
  timeout: 30000
kafka:
    bootstrap-server: 10.96.24.141:9093
kafkacache:
  topic: CACHE_HUB_NOTIFY
product-command:
  topic: PRODUCT
  groupId: PRODUCT_LOCAL
  autoStartup: true